In [2]:
import numpy as np

In [3]:
arr1= np.array([10,20,30,40,50])
print(np.sqrt(arr1))
print(np.exp(arr1))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


In [4]:
#STACK
arr1=np.array([10,20,30,40,50])
arr2=np.array([1,2,3,4,5])
harr=np.hstack((arr1,arr2))
print("Horizontal staking: ",harr)
varr=np.vstack((arr1,arr2))
print("Vertical stacking: ",varr)

Horizontal staking:  [10 20 30 40 50  1  2  3  4  5]
Vertical stacking:  [[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [5]:
#SORTING
arr3=np.array([1,5,3,10,6,8])
st=np.sort(arr3)
print("Ascending order: ",st)
st2=np.sort(arr3)[::-1]
print("Descending order: ",st2)

Ascending order:  [ 1  3  5  6  8 10]
Descending order:  [10  8  6  5  3  1]


In [9]:
#UNIQUE AND EQUAL
arr4=np.array([6,5,7,9,46,36,32,6,5,87,46])
arr5=np.array([6,5,7,9,46,36,32,6,5,87,46])
print(arr4>30)
print(np.array_equal(arr4,arr5))
print(np.unique(arr5))

[False False False False  True  True  True False False  True  True]
True
[ 5  6  7  9 32 36 46 87]
