In [5]:
import numpy as np

In [6]:
a0=np.array([[[1,2,3,4,5],[10,20,30,40,50]],[[6,7,8,9,10],[60,70,80,90,100]]])
a0
print(a0.shape)
print(a0.size)
print(a0.ndim)

(2, 2, 5)
20
3


In [8]:
import numpy as np
import time

# Size of the array/list
N = 10_000_000

# Using Python list
py_list = list(range(N))

start = time.time()
py_result = [x ** 2 for x in py_list]
end = time.time()
print("Time taken using Python list:", end - start, "seconds")

# Using NumPy array
np_array = np.arange(N)

start = time.time()
np_result = np_array ** 2
end = time.time()
print("Time taken using NumPy array:", end - start, "seconds")


Time taken using Python list: 1.2810957431793213 seconds
Time taken using NumPy array: 0.035816192626953125 seconds


In [10]:
lst = [1, 2, 3]
a = np.array(lst)
arr = np.array([1, 2, 3])
b = np.asarray(arr)
print(a)
print(b)

[1 2 3]
[1 2 3]


In [11]:
import numpy as np

arr = np.array([10, 20, 30], dtype=np.int32)
print(arr.data) 

In [13]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = a[1:3] 
print(b.base is a) 
c = a.copy()  
print(c.base is a)   
print(c.base) 

True
False
None


In [16]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

# Add b to each row of a manually (inefficient)
result = np.zeros_like(a)
print(result)
for i in range(a.shape[0]):
    result[i] = a[i] + b
result = a + b  # NumPy broadcasts b across each row
print(result)


[[0 0 0]
 [0 0 0]]
[[11 22 33]
 [14 25 36]]


In [17]:
import time

data = list(range(1_000_000))

start = time.time()
result = [x ** 2 for x in data]
end = time.time()

print("Python loop time:", end - start)
import numpy as np

data_np = np.arange(1_000_000)

start = time.time()
result_np = data_np ** 2  # Vectorized operation
end = time.time()

print("NumPy vectorized time:", end - start)


Python loop time: 0.21150445938110352
NumPy vectorized time: 0.0024492740631103516


In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b  # No loop!
print(result)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
result = a + b  # Automatically broadcasts b across rows
print(result)
x = np.array([0, np.pi/2, np.pi])
y = np.sin(x)  # Applies sin to every element
print(y)
a = np.array([1, 2, 3, 4, 5])
a[a % 2 == 0] = 0  # Set even numbers to 0
print(a)

[5 7 9]
[[11 22 33]
 [14 25 36]]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[1 0 3 0 5]


In [19]:
a = np.array([[1, 2], [3, 4]], order='C')  # Default
print(a.flags['C_CONTIGUOUS'])  # True
print(a.flags['F_CONTIGUOUS'])  # False

b = np.array([[1, 2], [3, 4]], order='F')  # Column-major
print(b.flags['F_CONTIGUOUS'])  # True


True
False
True


In [20]:
import numpy as np

a = np.random.rand(1000000)
%timeit np.sqrt(a)


3.28 ms ± 337 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
import numpy as np

# Example dataset
data = np.array([10, 20, 30, 40, 50])

# Min-Max Normalization
normalized_data = (data - data.min()) / (data.max() - data.min())

print(normalized_data)


[0.   0.25 0.5  0.75 1.  ]


In [22]:
import numpy as np

# Arrays with different shapes
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Concatenate along axis 0 (rows)
merged = np.concatenate([a, b], axis=0)

print(merged)


[[1 2]
 [3 4]
 [5 6]]


In [23]:
import numpy as np

# Define a structured array
dtype = [('name', 'U10'), ('age', 'i4'), ('score', 'f4')]
data = np.array([('Alice', 25, 88.5),
                 ('Bob', 30, 92.3),
                 ('Charlie', 25, 85.1),
                 ('David', 30, 89.7),
                 ('Eve', 35, 91.4)],
                dtype=dtype)

# Sort by multiple fields: age, then score
sorted_data = np.sort(data, order=['age', 'score'])

print(sorted_data)


[('Charlie', 25, 85.1) ('Alice', 25, 88.5) ('David', 30, 89.7)
 ('Bob', 30, 92.3) ('Eve', 35, 91.4)]


In [24]:
import numpy as np

# Sample data
data = np.array([10, 12, 13, 14, 15, 100, 17, 18, 19, 20])

# Calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Calculate Z-scores
z_scores = (data - mean) / std_dev

# Define the threshold for outliers (e.g., Z-score > 3)
threshold = 3

# Filter out outliers
filtered_data = data[np.abs(z_scores) <= threshold]

print("Original Data:", data)
print("Filtered Data (without outliers):", filtered_data)


Original Data: [ 10  12  13  14  15 100  17  18  19  20]
Filtered Data (without outliers): [ 10  12  13  14  15 100  17  18  19  20]


In [26]:

# Dot product of vectors (1D arrays)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result_dot = np.dot(a, b)  # Result = 1*4 + 2*5 + 3*6
print(result_dot)  # Output: 32

# Matrix multiplication (2D arrays)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result_matrix_dot = np.dot(A, B)
print(result_matrix_dot)

# Matrix multiplication (2D arrays)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result_matmul = np.matmul(A, B)
print(result_matmul)
import numpy as np

# Matrix multiplication using the @ operator
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result_at_operator = A @ B
print(result_at_operator)


32
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [27]:
# Coefficient matrix A
A = np.array([[2, 3],
              [4, 1]])

# Constant matrix B
B = np.array([8, 7])

# Solve the system of equations
X = np.linalg.solve(A, B)

print("Solution (x, y):", X)

Solution (x, y): [1.3 1.8]


In [1]:
import numpy as np

# Square invertible matrix
A = np.array([[2, 3],
              [1, 4]])

# Singular matrix (non-invertible)
B = np.array([[2, 4],
              [1, 2]])

print("Matrix A:")
print(A)

# Inverse of A
inv_A = np.linalg.inv(A)
print("\nInverse of A using inv():")
print(inv_A)

# Pseudoinverse of A
pinv_A = np.linalg.pinv(A)
print("\nPseudoinverse of A using pinv():")
print(pinv_A)

print("\nMatrix B (singular):")
print(B)

# Pseudoinverse of B (works)
pinv_B = np.linalg.pinv(B)
print("\nPseudoinverse of B using pinv():")
print(pinv_B)

# Inverse of B (will fail if uncommented)
# inv_B = np.linalg.inv(B)  # This will raise a LinAlgError


Matrix A:
[[2 3]
 [1 4]]

Inverse of A using inv():
[[ 0.8 -0.6]
 [-0.2  0.4]]

Pseudoinverse of A using pinv():
[[ 0.8 -0.6]
 [-0.2  0.4]]

Matrix B (singular):
[[2 4]
 [1 2]]

Pseudoinverse of B using pinv():
[[0.08 0.04]
 [0.16 0.08]]


In [2]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

# Simulated large dataset
data = np.random.rand(1000000)

# Create rolling windows of size 3
windowed = sliding_window_view(data, window_shape=3)

# Apply mean on each window
rolling_means = windowed.mean(axis=1)

print("First 5 rolling means:", rolling_means[:5])


First 5 rolling means: [0.7538099  0.75841836 0.65672427 0.47956937 0.41020567]


In [3]:
import numpy as np
import time

# Initialize a fixed-size buffer for streaming data
BUFFER_SIZE = 100
WINDOW_SIZE = 10

buffer = np.zeros(BUFFER_SIZE)
index = 0

# Simulated sensor data stream generator
def get_sensor_data():
    return np.random.rand() * 100  # random float between 0 and 100

# Function to update buffer in a circular way
def update_buffer(buffer, value, index):
    buffer[index % BUFFER_SIZE] = value
    return buffer

# Function to compute rolling average (on last WINDOW_SIZE points)
def compute_rolling_average(buffer, index, window_size):
    if index < window_size:
        return np.mean(buffer[:index])
    start = (index - window_size) % BUFFER_SIZE
    if start + window_size <= BUFFER_SIZE:
        return np.mean(buffer[start:start + window_size])
    else:
        # Wrap around circular buffer
        return np.mean(np.concatenate((buffer[start:], buffer[:(start + window_size) % BUFFER_SIZE])))

# Simulate real-time processing
for i in range(150):  # simulate 150 data points
    new_data = get_sensor_data()
    buffer = update_buffer(buffer, new_data, index)
    avg = compute_rolling_average(buffer, index + 1, WINDOW_SIZE)
    
    print(f"Data Point {i+1:3}: {new_data:.2f} | Rolling Avg (last {WINDOW_SIZE}): {avg:.2f}")
    
    index += 1
    time.sleep(0.1)  # simulate real-time delay


Data Point   1: 60.12 | Rolling Avg (last 10): 60.12
Data Point   2: 56.59 | Rolling Avg (last 10): 58.35
Data Point   3: 90.69 | Rolling Avg (last 10): 69.13
Data Point   4: 2.78 | Rolling Avg (last 10): 52.54
Data Point   5: 14.09 | Rolling Avg (last 10): 44.85
Data Point   6: 96.10 | Rolling Avg (last 10): 53.39
Data Point   7: 38.91 | Rolling Avg (last 10): 51.32
Data Point   8: 91.42 | Rolling Avg (last 10): 56.34
Data Point   9: 65.97 | Rolling Avg (last 10): 57.41
Data Point  10: 20.91 | Rolling Avg (last 10): 53.76
Data Point  11: 49.28 | Rolling Avg (last 10): 52.67
Data Point  12: 88.73 | Rolling Avg (last 10): 55.89
Data Point  13: 55.98 | Rolling Avg (last 10): 52.42
Data Point  14: 21.99 | Rolling Avg (last 10): 54.34
Data Point  15: 39.11 | Rolling Avg (last 10): 56.84
Data Point  16: 61.19 | Rolling Avg (last 10): 53.35
Data Point  17: 90.27 | Rolling Avg (last 10): 58.48
Data Point  18: 52.47 | Rolling Avg (last 10): 54.59
Data Point  19: 20.22 | Rolling Avg (last 10): 

In [5]:
import numpy as np

a = np.array([1, 2, 3], dtype=np.int32)
b = np.array([4.5, 5.5, 6.5])  # default is float64

# Ensure consistency
common_dtype = np.result_type(a, b)
a = a.astype(common_dtype)
b = b.astype(common_dtype)

# Now safe to concatenate
c = np.concatenate([a, b])
print(c, c.dtype)


[1.  2.  3.  4.5 5.5 6.5] float64
