In [3]:
def addition(a,b):
    s=a+b
    return s

In [4]:
addition(10,20)

30

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [8]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [10]:
a0=np.array(10)
a0

array(10)

In [11]:
a1=np.array([10,20,30,40,50])
a1

array([10, 20, 30, 40, 50])

In [13]:
a2=np.array([[1,2,3,4,5],[10,20,30,40,50]])
a2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [16]:
a3=np.array([[[1,2,3,4,5],[10,20,30,40,50]],[[6,7,8,9,10],[60,70,80,90,100]]])
a3

array([[[  1,   2,   3,   4,   5],
        [ 10,  20,  30,  40,  50]],

       [[  6,   7,   8,   9,  10],
        [ 60,  70,  80,  90, 100]]])

In [18]:
print(a0.shape)
print(a0.size)
print(a0.ndim)

()
1
0


In [19]:
print(a1.shape)
print(a1.size)
print(a1.ndim)

(5,)
5
1


In [20]:
print(a2.shape)
print(a2.size)
print(a2.ndim)

(2, 5)
10
2


In [21]:
print(a3.shape)
print(a3.size)
print(a3.ndim)

(2, 2, 5)
20
3


In [22]:
z=np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
a=np.ones((1,2))
a

array([[1., 1.]])

In [26]:
b=np.empty((2,2))
b

array([[2.12199579e-314, 9.54898106e-312],
       [6.87739379e-321, 9.54898106e-312]])

In [27]:
#List indexing
l=[1,2,3,4]
l

[1, 2, 3, 4]

In [28]:
l[1:3]

[2, 3]

In [32]:
#numpy array indexing
a1[1:3]

array([20, 30])

In [31]:
a2[1][1:3]

array([20, 30])

In [33]:
#NUMPY INDEXING
a1=np.array([11,22,33,44,55])
a2=np.array([10,20,30,40,50])
print("Addition: ",a1+a2)
print("Subtraction: ",a1-a2)
print("Scalar multiplication: ",a1*5,"\n",a2*2)
print("Division: ",a1/a2)
print("Dot product: ", np.dot(a1,a2))

Addition:  [ 21  42  63  84 105]
Subtraction:  [1 2 3 4 5]
Scalar multiplication:  [ 55 110 165 220 275] 
 [ 20  40  60  80 100]
Division:  [1.1 1.1 1.1 1.1 1.1]
Dot product:  6050


In [41]:
#RESHAPING AND FLATTENING
a5=np.arange(6)
a5
a5=a5.reshape(3,2)
a5
a5=a5.flatten()
a5

array([0, 1, 2, 3, 4, 5])

In [46]:
#ARRAY CONCATENATION AND SPLITTING
b1=np.array([[1,3],[5,7]])
b2=np.array([[9,11]])
b3=np.concatenate((b1,b2),axis=0)
print(b3)
s=np.split(b3,3)
print(s)

[[ 1  3]
 [ 5  7]
 [ 9 11]]
[array([[1, 3]]), array([[5, 7]]), array([[ 9, 11]])]


In [47]:
#MATHEMATICAL AND STATISTICAL FUNCTIONS
b1=np.array([10,20,30,40,50])
print(np.sum(b1))
print(np.mean(b1))
print(np.std(b1))
print(np.max(b1))
print(np.min(b1))
print(np.argmax(b1))
print(np.argmin(b2))

150
30.0
14.142135623730951
50
10
4
0
