In [1]:
import random as rn
import numpy as np

In [2]:
a0=np.array([rn.randint(1,20) for i in range(5)])
a0

array([ 6,  5,  2, 17,  6])

In [4]:
a1=np.array([[rn.randint(1,20) for j in range(5)] for i in range(2)])
a1

array([[ 7,  4, 11, 14, 11],
       [ 4, 17,  6, 17, 18]])

In [5]:
a2=np.array([[[rn.randint(1,20) for j in range(5)] for k in range(2)]for i in range(2)])
a2

array([[[19, 18,  2, 16,  4],
        [17, 10, 19,  7, 20]],

       [[20,  2,  5, 14,  4],
        [12, 13,  6, 20,  1]]])

In [6]:
print(a0.shape)
print(a0.size)
print(a0.ndim)

(2, 5)
10
2


In [7]:
print(a1.shape)
print(a1.size)
print(a1.ndim)

(2, 5)
10
2


In [8]:
print(a2.shape)
print(a2.size)
print(a2.ndim)

(2, 2, 5)
20
3


In [9]:
#NUMPY INDEXING
a1=np.array([rn.randint(1,20) for i in range(5)])
a2=np.array([rn.randint(1,20) for i in range(5)])
print("Addition: ",a1+a2)
print("Subtraction: ",a1-a2)
print("Scalar multiplication: ",a1*5,"\n",a2*2)
print("Division: ",a1/a2)
print("Dot product: ", np.dot(a1,a2))

Addition:  [17 25 16 22 30]
Subtraction:  [ 15 -15  -4  16 -10]
Scalar multiplication:  [80 25 30 95 50] 
 [ 2 40 20  6 40]
Division:  [16.          0.25        0.6         6.33333333  0.5       ]
Dot product:  433


In [10]:
b1=np.array([rn.randint(1,20) for i in range(5)])
b2=np.array([[9,11]])
print(np.sum(b1))
print(np.mean(b1))
print(np.std(b1))
print(np.max(b1))
print(np.min(b1))
print(np.argmax(b1))
print(np.argmin(b2))

49
9.8
5.114684741017769
19
4
4


NameError: name 'b2' is not defined